### ISSUE TITLE
Investigate why there is no error message for wrong login

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14664]
In #14556 an error message was implemented for unsuccessful logins, this error message does not show up anymore after the merge. Investigate why, and fix it.

**Comment by a20jonda** [comment]
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/3ce73a87-580c-43b5-9280-319e99589c23)

Message is now showing after fetching to latest.

**Comment by a20jonda** [comment]
This issue have been solved

**Comment by b22marah** [comment]
Still doesn´t work for me or @a22willi, therefor we assign the issue to another group member, that this doesn´t work for to fully test and fix the issue.
