### ISSUE TITLE
Count number of submissions for an assignment

### ISSUE THREAD

**Issue by klump** [HGustavs/LenaSYS#2282]
It would be nice if I as a teacher could see how many times this assignment was graded before. Sometimes it makes a differences if a students submitted the assignment 20 times or just for the second time...

**Comment by a13arnhe** [comment]
As userAnswers only stores and updates the most recent try of a test/assignment the teachers are not able to see the history of it. However when I implemented the max amount of tries and lock on tests until a teacher unlocks it I needed to see how many times a certain user has taken a certain test. So now the database currently has a table that stores exactly that. This table is named 'duggaTries'. #1910 is the issue that implemented that table.

**Comment by klump** [comment]
In that case I would make the contact to the teacher optional. Some assignments might allow only 10 tries, so that the assignment should close itself (unlocking of the assignment not directly intended).

**Comment by a15timbe** [comment]
Solved in #3516

**Comment by a15ponja** [comment]
Due to the assignee slightly misread the issue at hand it was not really solved, the thing that was solved was the number of times a submission have been made by a user.
