### ISSUE TITLE
If we have magic headings showing and we click on them for resort they disappear

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#2433]
If we have magic headings showing and we click on them for resort they disappear. On scrolling they will reappear properly formatted.

**Comment by HGustavs** [comment]
Unclear...

are we saying that the headings disappear?

Screenshot?

**Comment by c14emian** [comment]
Bump

**Comment by HGustavs** [comment]
Its a marking view issue, and I think it may have been resolved.

To test it, one needs to go to the marking view and re-sort the list a couple of times to see if the headings act up.

**Comment by a15freed** [comment]
The issue is still there
![image](https://cloud.githubusercontent.com/assets/26706932/25328559/98232a44-28d8-11e7-9f0a-3c73f0e37560.png)

and after clicking the header...
![image](https://cloud.githubusercontent.com/assets/26706932/25328604/c6528612-28d8-11e7-9adf-7ea0907de8e7.png)
