### ISSUE TITLE
The round "New item" button covers information

### ISSUE THREAD

**Issue by a15matab** [HGustavs/LenaSYS#3576]
The button covers information if there are too many duggas. Maybe make it movable or make it always stay below the last dugga in the list. 

![bug1](https://cloud.githubusercontent.com/assets/26706785/25738067/5a34f0b8-317b-11e7-9506-af5c2d83b334.png)

**Comment by a15elibr** [comment]
Closing issue since it has been resolved.

**Comment by A15cecal** [comment]
Noticed now when there's more items in the list that this issue still needs some fixing. Will open this and work with it again.

**Comment by A15cecal** [comment]
Solved.
