### ISSUE TITLE
Check mark in Accessed.php changes the name of the person. 

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#6068]
When you press the check mark icon next to the persons name it will change the name of the person. 

Before pressing the check mark on Alex. 
![image](https://user-images.githubusercontent.com/49199285/56286682-a2ce8c00-611a-11e9-99e8-d8976e273475.png)

![image](https://user-images.githubusercontent.com/49199285/56287120-d6f67c80-611b-11e9-9e5c-3239f7e0751e.png)

And after you press the check mark the name will change, in this case Alex Bridgeman will have another name (Anders in this case) when you press on him. 

![image](https://user-images.githubusercontent.com/49199285/56287275-2fc61500-611c-11e9-9ec7-bfeb76317f2d.png)

![image](https://user-images.githubusercontent.com/49199285/56287308-48cec600-611c-11e9-9cc5-7e002fe5b5fd.png)

**Comment by a17alevu** [comment]
It jumps to the person under, so if you press once on the check mark on Alex he will have Anders' name,, if i press again he will get Anita and so on...

**Comment by a17alevu** [comment]
This is also the same with their surnames, meaning that both first name and last name will change.

**Comment by a17maxsj** [comment]
Fixed?

**Comment by a17robes** [comment]
This is not fixed, and I don't know how to fix it.. maybe someone else in the group knows?

**Comment by a17robes** [comment]
@a17maxsj

**Comment by a16joare** [comment]
I think that this is a SortableTable problem. It seems like the column values is updated in the table and database but the column remain unsorted. If you update for example "firstname" and then reload the page the changed first namne is still there.  

Not sure but i think that the problem is located in the reRender function.

**Comment by c14jonfr** [comment]
I've noticed a behaviour that hasn't been brought up yet, it could be it's own issue but I believe the root cause is the same (or at least something very similar).

When a column is sorted (First Name for example), and the user clicks the name to edit it, it will show the name of the person who previously "had that spot". Clicking the green check mark fixes this. You can tell that the rows "shuffles around" a bit and then it seems to be properly sorted. 

We have not been able to come up with a solution to this issue yet.

**Comment by a18ismca** [comment]
I have noticed that the check box is not closed even when doing other activities (such as sorting or modifying other attributes in the same table), which I think could be an own issue. For example, someone could sorting another column or modify other types data while the checkbox is still visible.

**Comment by b18jonli** [comment]
If you update a cell after it shows the wrong value, it will start to show the right value again, like e.g. 
1: update cell 
2: re-sort table
3: click on cell to edit -> wrong value
4. press enter to update cell -> no change in value
5. click on cell to edit -> correct value

Also, the table gets increasingly slow if you continuously update a cell and re-sort the table over and over.

**Comment by b18jonli** [comment]
Changing the filter (e.g. only showing teachers) further illustrates the issue, where names that should be filtered out can still appear as values when editing a cell.

**Comment by b18jonli** [comment]
The problem seems to be that sortableTable.js, on row 109, sortableTable.currentTable.getRow(rowno) returns the wrong data for that rowno. 
The function getRow() returns the value of tbl.tblbody[rowno] which indicates that the tblbody rows do not mirror the actually rendered rows.

**Comment by b18jonli** [comment]
Actually no, after a tbl.tblbody.sort(sortableInternalSort) on row 330 the tbl.tblbody rows DO match the displayed rows.

**Comment by b18jonli** [comment]
@HGustavs

**Comment by HGustavs** [comment]
I really dont know we noticed the same thing and I tried to find the reason and did not.

**Comment by HGustavs** [comment]
Is it only for name or all columns?

Check the ids stored in the data. For some reason perhaps it is wrong all the way from the database.

**Comment by HGustavs** [comment]
Seems to be a bug question is how wide spread it is .

**Comment by b18jonli** [comment]
At least the columns username, firstname and lastname are incorrect. The “coldata” value in clickedInternal contains the correct UID-name pair, but for a different row than the clicked one.

It is possible to get the correct UID from the cliched element, and then get the row with a matching UID, but perhaps that would only “mask” the actual issue.

**Comment by b18jonli** [comment]
The amount of calls to the reRender are 2^cell_updates, e.g. after one cell update, reRender is called twice but after 5 cell updates, reRender is called 32 times. Is it possible the table is somehow duplicated after a cell update?

**Comment by b18jonli** [comment]
I added some console debugging to show that the table is duplicated (and reordering only works on one of the copies) to branch G2-2020-W16-#6068. 
(commit 289735936767c0f98543f3cdc7f7b90f5148f708)

**Comment by b18jonli** [comment]
I am pretty sure that the problem is the returnedAccess() function in accessed.js where the table instance is created, it gets called every cell update.

**Comment by b18alegu** [comment]
This issue was merged into the W16 master. I'm closing this one now.
