### ISSUE TITLE
Sectioned: Date gets cut off

### ISSUE THREAD

**Issue by a17ludca** [HGustavs/LenaSYS#6767]
There are some breakpoints when resizing the window that makes the date on a row not show to it's full extent. 
Example: 
![image](https://user-images.githubusercontent.com/37799006/57378153-5e2b9300-71a4-11e9-97f1-62201950e8d7.png)

**Comment by b16johso** [comment]
This was fixed a few weeks ago

**Comment by a17ludca** [comment]
@b16johso Still appears after the latest merge so it needs to be fixed again I suppose. 🤷‍♂

**Comment by c17johha** [comment]
Firefox cuts off the time:
![image](https://user-images.githubusercontent.com/49199825/57852001-45456200-77e2-11e9-8146-8e90526a4498.png)

Chrome doesn't show the year:
![image](https://user-images.githubusercontent.com/49199825/57852048-65752100-77e2-11e9-8556-75d33dcb2ba9.png)

**Comment by c17julka** [comment]
@c17johha From what I can remember, when it was fixed it was changed so that only the month/day/time was shown on smaller screens. 

For me, the problem is the same on both Chrome and Firefox.
